app = 'fly-io-wild-fire-1232'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '12345'

[[services]]
  protocol = 'udp'
  internal_port = 12345   # コンテナ内でリッスンするポート
  external_port = 12345   # 外部に公開するポート

  [[services.ports]]
    port = 12345           # 外部公開用のポート番号
    handlers = ['udp']     # UDPプロトコルを指定
