app = 'fly-io-wild-fire-1232'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '80'

[[services]]
  internal_port = 80
  protocol = 'tcp'

[[services.ports]]
   port = 80
  handlers = ["http"]

[services.http_checks]
    grace_period = "1m"
    interval = "0"  # ヘルスチェック無効化
