app = 'fly-io-wild-fire-1232'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '12345'

[[services]]
  internal_port = 12345
  protocol = 'udp'

  [[services.ports]]
    port = 12345