app = 'fly-io-summer-dew-1267'

[build]
  image = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "udp"  # UDP通信に変更

  [[services.ports]]
    handlers = ["udp"]  # UDP用に設定
    port = 12345         # 使用するポートを指定（例：12345）

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
